Remove the incorrect label flag when creating AWS GPU machine-set
The following command fails:
oc create -f /tmp/gpu-machineset.json -l gpu-machineset=true

Since passing label to the oc create is not supported:
error: no objects passed to create

Signed-off-by: manosnoam <nmanos@redhat.com>